### ISSUE TITLE
Support for A5-38-08 (Eltako FUD61)

### ISSUE THREAD

**Issue by codmpm** [owagner/eno2mqtt#2]
Hi Oliver,

is support for Eltako's FUD61 planned?

```
WARNUNG: Error while reading device list file devicelist.txt in line 2
java.lang.IllegalArgumentException: Unsupported EEP A5-38-08 
    at com.tellerulam.eno2mqtt.DeviceManager.readDeviceList(DeviceManager.java:55)
at com.tellerulam.eno2mqtt.Main.main(Main.java:60)
```

Regards,
Patrik

**Comment by zhaijohan** [comment]
Hi Patrik,

do you also use the USB300? 

Regards, 

Johan

**Comment by codmpm** [comment]
Hi,

yes. But in the meantime I am now bridging the FUD61 over FHEM through mqtt.

Regards,
Patrik

**Comment by zhaijohan** [comment]
Hi, 
I see ! Could you actually use the eno2mqtt with the FUD61?  I am having the issue, that eno2mqtt doesnt initialize my USB300 , even if it is recognized by using the command lsusb. Did you also have this kind of problem?

**Comment by codmpm** [comment]
Hi,

as I said, I'm not using eno2mqtt cause it can't talk to the FUD61. I had no initialisation problems with the USB300 though. You have to add your user to the `dialout` group on linux, so it can access the usb port.

Cheers, 
p

**Comment by zhaijohan** [comment]
Hi, I'm sorry to bother you, but if I am typing `ls -la` -> I will get this output: `crw-rw-rw-  1 root dialout 188,   0 Jul 24 22:57 ttyUSB0`.  Is this right? My username is already in the dialout group, but I still get this error message: 

`INFO: ESP(1): Using serial port /dev/ttyUSB0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 24, 2016 10:57:24 PM com.tellerulam.eno2mqtt.ESP3Connector sendInitPackets
INFO: ESP(1): Resetting device...
WARNING: ESP(1): Error in ESP3 communication handler, retrying in 10s
java.io.EOFException
    at com.tellerulam.eno2mqtt.ESP3Connector.doIt(ESP3Connector.java:274)
    at com.tellerulam.eno2mqtt.ESP3Connector.run(ESP3Connector.java:215)

Regards, Johan

**Comment by codmpm** [comment]
That looks more like there are some Java libraries not installed - but I'm not a Java person. Maybe the author of this software can help.
