### ISSUE TITLE
TCM310 with busware.de firmware supported?

### ISSUE THREAD

**Issue by ctr49** [owagner/eno2mqtt#5]
As far as I know a TCM310 (running the busware.de firmware) should be ESP3 compatible. I was using the device fine with FHEM, but want to switch to node-red.
Using your Java bridge I get the following error when starting
```
# LC_ALL=C java -jar eno2mqtt.jar eno.esp3=/dev/eul eno.deviceList=/etc/node-red/eno.map 
Dec 20, 2016 12:41:55 AM com.tellerulam.eno2mqtt.Main main
INFO: eno2mqtt V0.6 (C) 2015 Oliver Wagner <owagner@tellerulam.com>
Dec 20, 2016 12:41:55 AM com.tellerulam.eno2mqtt.DeviceManager readDeviceList
INFO: Read 0 devices: []
Dec 20, 2016 12:41:56 AM com.tellerulam.eno2mqtt.MQTTHandler doConnect
INFO: Connecting to MQTT broker tcp://localhost:1883 with CLIENTID=eno2mqtt and TOPIC PREFIX=eno/
Dec 20, 2016 12:41:56 AM com.tellerulam.eno2mqtt.MQTTHandler doConnect
INFO: Successfully connected to broker, subscribing to eno/set/#
Dec 20, 2016 12:41:56 AM com.tellerulam.eno2mqtt.ESP3Connector$SerialConnector connect
INFO: ESP(1): Using serial port /dev/eul
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Dec 20, 2016 12:41:56 AM com.tellerulam.eno2mqtt.ESP3Connector sendInitPackets
INFO: ESP(1): Resetting device...
Dec 20, 2016 12:41:56 AM com.tellerulam.eno2mqtt.ESP3Connector run
WARNING: ESP(1): Error in ESP3 communication handler, retrying in 10s
java.io.EOFException
	at com.tellerulam.eno2mqtt.ESP3Connector.doIt(ESP3Connector.java:274)
	at com.tellerulam.eno2mqtt.ESP3Connector.run(ESP3Connector.java:215)

Dec 20, 2016 12:42:06 AM com.tellerulam.eno2mqtt.ESP3Connector$SerialConnector connect
INFO: ESP(1): Using serial port /dev/eul
Dec 20, 2016 12:42:06 AM com.tellerulam.eno2mqtt.ESP3Connector sendInitPackets
INFO: ESP(1): Resetting device...
Dec 20, 2016 12:42:06 AM com.tellerulam.eno2mqtt.ESP3Connector run
WARNING: ESP(1): Error in ESP3 communication handler, retrying in 10s
java.io.EOFException
	at com.tellerulam.eno2mqtt.ESP3Connector.doIt(ESP3Connector.java:274)
	at com.tellerulam.eno2mqtt.ESP3Connector.run(ESP3Connector.java:215)

Dec 20, 2016 12:42:11 AM com.tellerulam.eno2mqtt.ESP3Connector$ConnectionChecker run
SEVERE: No more active connections, terminating
```

Any ideas @owagner ?

**Comment by HarterHorst** [comment]
Exact same here. Have you found a solution?

**Comment by HarterHorst** [comment]
same here. Have you found a solution?

**Comment by ctr49** [comment]
I'm currently running a simple listener based on the Eno SDK, could not find a solution for this project.
